<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tbl_diem".
 *
 * @property int $diem_id
 * @property float $diemX
 * @property float $diemY
 * @property float $diemZ
 * @property string $ghichu
 * @property string $mahocphan
 * @property int $msv
 * @property int $dotdk_id
 *
 * @property TblHocphan $mahocphan0
 * @property TblSinhvien $msv0
 * @property TblSinhvien $dotdk_id0
 */
class TblDiem extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tbl_diem';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
//            [['diem_id', 'diemX', 'diemY', 'diemZ', 'ghichu', 'mahocphan', 'msv'], 'required'],
            [['diem_id', 'msv','dotdk_id'], 'integer'],
            [['diemX', 'diemY', 'diemZ'], 'number'],
            [['ghichu'], 'string'],
            [['mahocphan'], 'string', 'max' => 40],
            [['diem_id'], 'unique'],
            [['mahocphan'], 'exist', 'skipOnError' => true, 'targetClass' => TblHocphan::className(), 'targetAttribute' => ['mahocphan' => 'mahocphan']],
            [['msv'], 'exist', 'skipOnError' => true, 'targetClass' => TblSinhvien::className(), 'targetAttribute' => ['msv' => 'msv']],
            [['dotdk_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblDotdk::className(), 'targetAttribute' => ['dotdk_id' => 'dotdk_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'diem_id' => 'Mã điểm',
            'diemX' => 'Điểm X',
            'diemY' => 'Điểm Y',
            'diemZ' => 'Điểm Z',
            'ghichu' => 'Ghi chú',
            'mahocphan' => 'Học phần',
            'msv' => 'Mã sinh viên',
            'dotdk_id'=>'Đợt Đăng Ký'
        ];
    }

    /**
     * Gets query for [[Mahocphan0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMahocphan0()
    {
        return $this->hasOne(TblHocphan::className(), ['mahocphan' => 'mahocphan']);
    }
    public function dotdk_id0()
    {
        return $this->hasOne(TblDotdk::className(), ['dotdk_id' => 'dotdk_id']);
    }
    /**
     * Gets query for [[Msv0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMsv0()
    {
        return $this->hasOne(TblSinhvien::className(), ['msv' => 'msv']);
    }
    public function beforeSave($insert)
    {


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
