<?php

namespace common\models;

use phpDocumentor\Reflection\Types\This;
use Yii;
use function Symfony\Component\String\s;

/**
 * This is the model class for table "tbl_dotdk".
 *
 * @property int $dotdk_id
 * @property string $name
 * @property bool $status
 *
 * @property TblLophocphan[] $tblLophocphans
 */
class TblDotdk extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tbl_dotdk';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'boolean'],
            [['name'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'dotdk_id' => 'Dotdk ID',
            'name' => 'Name',
            'status' => 'Status',
        ];
    }

    /**
     * Gets query for [[TblLophocphans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTblLophocphans()
    {
        return $this->hasMany(TblLophocphan::className(), ['dotdk_id' => 'dotdk_id']);
    }

    public function beforeDelete()
    {
        $dslhp= TblLophocphan::findAll(["dotdk_id"=>$this->dotdk_id]);
        foreach ($dslhp as $item) {


            $item->delete();

        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $dotdks=TblDotdk::findAll(["status"=>'1']);
        if(count($dotdks)>0&&$this->status==1)
        {
            ?>
            <script>
                alert("Đã tồn tại một đợt đăng ký đang hoạt động vui lòng kiểm tra lại!");
            </script>
<?php
            return null;
        }

        return parent::beforeSave($insert); 
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($this->status==1)
        {
            $file=fopen("newdotdk.txt","w");
            fwrite($file,$this->dotdk_id);
            fclose($file);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
