<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tbl_khoa".
 *
 * @property string $makhoa
 * @property string $tenkhoa
 *
 * @property TblNganh[] $tblNganhs
 */
class TblKhoa extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tbl_khoa';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['makhoa', 'tenkhoa'], 'required'],
            [['makhoa'], 'string', 'max' => 20],
            [['tenkhoa'], 'string', 'max' => 400],
            [['makhoa'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'makhoa' => 'Mã khoa',
            'tenkhoa' => 'Tên khoa',
        ];
    }

    /**
     * Gets query for [[TblNganhs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTblNganhs()
    {
        return $this->hasMany(TblNganh::className(), ['makhoa' => 'makhoa']);
    }
    public function beforeDelete()
    {
        $nganhs = TblNganh::findAll(['makhoa'=>$this->makhoa]);

        foreach ($nganhs as $nganh)
        {
            $nganh->delete($nganh->manganh);
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
