<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tbl_tendanhmuc".
 *
 * @property int $danhmuc_id
 * @property string $tendanhmuc
 *
 * @property TblBaidang[] $tblBaidangs
 */
class TblTendanhmuc extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tbl_tendanhmuc';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['danhmuc_id', 'tendanhmuc'], 'required'],
            [['danhmuc_id'], 'integer'],
            [['tendanhmuc'], 'string', 'max' => 400],
            [['danhmuc_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'danhmuc_id' => 'Mã danh mục',
            'tendanhmuc' => 'Tên danh mục',
        ];
    }

    /**
     * Gets query for [[TblBaidangs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTblBaidangs()
    {
        return $this->hasMany(TblBaidang::className(), ['danhmuc_id' => 'danhmuc_id']);
    }
   public function beforeDelete()
    {
        $baidang=TblBaidang::findAll(["danhmuc_id"=>$this->danhmuc_id]);
        foreach ($baidang as $item) {

            $item->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
